-- =============================================================
-- Sistema de Gestión de Prácticas Académicas v1.0
-- Oracle 10g+ / SQL*Plus / Compatible con ojdbc14.jar
-- Crea los 34 objetos tabla y 5 vistas solicitados en el proyecto.
-- Ejecución sugerida: @00_schema_oracle_10g_39_objetos.sql
-- =============================================================

SET DEFINE OFF;


CREATE TABLE ROL (

    ID_ROL NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    DESCRIPCION VARCHAR2(400),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL),
CONSTRAINT UK_ROL_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE USUARIO (

    ID_USUARIO NUMBER(10) NOT NULL,
    ID_ROL NUMBER(10),
    NOMBRE VARCHAR2(80) NOT NULL,
    APELLIDO VARCHAR2(80) NOT NULL,
    TIPO_DOCUMENTO VARCHAR2(20),
    DOCUMENTO VARCHAR2(30),
    EMAIL VARCHAR2(120) NOT NULL,
    CORREO VARCHAR2(120),
    CONTRASENA VARCHAR2(200),
    PASSWORD VARCHAR2(200),
    TIPO_USUARIO VARCHAR2(30) DEFAULT 'ESTUDIANTE' NOT NULL,
    ROL VARCHAR2(30) DEFAULT 'ESTUDIANTE' NOT NULL,
    TELEFONO VARCHAR2(30),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_USUARIO_DOCUMENTO UNIQUE (DOCUMENTO),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);

CREATE TABLE PROGRAMA (

    ID_PROGRAMA NUMBER(10) NOT NULL,
    ID_GLO_PROGRAMA VARCHAR2(30),
    NOMBRE VARCHAR2(150) NOT NULL,
    CODIGO VARCHAR2(30),
    PROYECTO VARCHAR2(200),
    RESOLUCION_MIN VARCHAR2(60),
    DESCRIPCION VARCHAR2(1000),
    FACULTAD VARCHAR2(120),
    DURACION_SEMESTRES NUMBER(2) DEFAULT 8,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_PROGRAMA PRIMARY KEY (ID_PROGRAMA),
CONSTRAINT UK_PROGRAMA_CODIGO UNIQUE (CODIGO)
);

CREATE TABLE CURSO (

    ID_CURSO NUMBER(10) NOT NULL,
    ID_PROGRAMA NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(120) NOT NULL,
    CODIGO VARCHAR2(30),
    SEMESTRE VARCHAR2(20),
    CREDITOS NUMBER(2) DEFAULT 3,
    DESCRIPCION VARCHAR2(1000),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY (ID_CURSO),
CONSTRAINT FK_CURSO_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA(ID_PROGRAMA)
);

CREATE TABLE INSTITUCION (

    ID_INSTITUCION NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(150) NOT NULL,
    NIT VARCHAR2(40),
    DIRECCION VARCHAR2(200),
    CIUDAD VARCHAR2(80),
    MUNICIPIO VARCHAR2(80),
    TELEFONO VARCHAR2(30),
    EMAIL VARCHAR2(120),
    REPRESENTANTE VARCHAR2(120),
    CONTACTO_NOMBRE VARCHAR2(120),
    SITIO_WEB VARCHAR2(150),
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    FECHA_INICIO_CONVENIO DATE,
    FECHA_FIN_CONVENIO DATE,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_INSTITUCION PRIMARY KEY (ID_INSTITUCION),
CONSTRAINT UK_INSTITUCION_NIT UNIQUE (NIT)
);

CREATE TABLE PRACTICA (

    ID_PRACTICA NUMBER(10) NOT NULL,
    ID_PROGRAMA NUMBER(10),
    ID_CURSO NUMBER(10),
    NOMBRE VARCHAR2(150) NOT NULL,
    TITULO VARCHAR2(150),
    DESCRIPCION VARCHAR2(1000),
    OBJETIVOS VARCHAR2(1000),
    NUMERO_PRACTICA NUMBER(2),
    HORAS_REGLAMENTARIAS NUMBER(5) DEFAULT 0,
    HORAS_REQUERIDAS NUMBER(5) DEFAULT 0,
    TIPO_MODALIDAD VARCHAR2(60),
    TIPO_PRACTICA VARCHAR2(80),
    PERIODO_ACADEMICO VARCHAR2(30),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ESTADO VARCHAR2(30) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_PRACTICA PRIMARY KEY (ID_PRACTICA),
CONSTRAINT FK_PRACTICA_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA(ID_PROGRAMA),
    CONSTRAINT FK_PRACTICA_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

CREATE TABLE GRUPO (

    ID_GRUPO NUMBER(10) NOT NULL,
    ID_CURSO NUMBER(10),
    ID_PRACTICA NUMBER(10),
    ID_DOCENTE NUMBER(10),
    ID_INSTITUCION NUMBER(10),
    NOMBRE VARCHAR2(80) NOT NULL,
    NOMBRE_GRUPO VARCHAR2(80),
    PERIODO_ACADEMICO VARCHAR2(30),
    SEMESTRE VARCHAR2(20),
    ANIO NUMBER(4),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    CUPO_MAXIMO NUMBER(4),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_GRUPO PRIMARY KEY (ID_GRUPO),
CONSTRAINT FK_GRUPO_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    CONSTRAINT FK_GRUPO_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA),
    CONSTRAINT FK_GRUPO_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_GRUPO_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION)
);

CREATE TABLE CONVENIO_INSTITUCION (

    ID_CONVENIO_INSTITUCION NUMBER(10) NOT NULL,
    ID_INSTITUCION NUMBER(10) NOT NULL,
    NUMERO_CONVENIO VARCHAR2(60),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    OBJETO VARCHAR2(1000),
    ESTADO VARCHAR2(20) DEFAULT 'VIGENTE' NOT NULL,
    CONSTRAINT PK_CONV_INST PRIMARY KEY (ID_CONVENIO_INSTITUCION),
CONSTRAINT FK_CONVENIO_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION)
);

CREATE TABLE SUPERVISOR_INSTITUCION (

    ID_SUPERVISOR_INSTITUCION NUMBER(10) NOT NULL,
    ID_INSTITUCION NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10),
    NOMBRE VARCHAR2(120) NOT NULL,
    CARGO VARCHAR2(80),
    CORREO VARCHAR2(120),
    TELEFONO VARCHAR2(30),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_SUP_INST PRIMARY KEY (ID_SUPERVISOR_INSTITUCION),
CONSTRAINT FK_SUP_INST_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
    CONSTRAINT FK_SUP_INST_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE OFERTA_PRACTICA (

    ID_OFERTA_PRACTICA NUMBER(10) NOT NULL,
    ID_INSTITUCION NUMBER(10) NOT NULL,
    ID_PRACTICA NUMBER(10),
    TITULO VARCHAR2(150) NOT NULL,
    DESCRIPCION VARCHAR2(1000),
    CUPO NUMBER(4),
    FECHA_PUBLICACION DATE DEFAULT SYSDATE,
    FECHA_CIERRE DATE,
    ESTADO VARCHAR2(20) DEFAULT 'PUBLICADA' NOT NULL,
    CONSTRAINT PK_OFERTA_PRAC PRIMARY KEY (ID_OFERTA_PRACTICA),
CONSTRAINT FK_OFERTA_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
    CONSTRAINT FK_OFERTA_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA)
);

CREATE TABLE COMPATIBILIDAD_INSTITUCION (

    ID_COMPATIBILIDAD NUMBER(10) NOT NULL,
    ID_INSTITUCION NUMBER(10) NOT NULL,
    ID_PRACTICA NUMBER(10) NOT NULL,
    NIVEL_COMPATIBILIDAD NUMBER(5,2),
    JUSTIFICACION VARCHAR2(1000),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_COMP_INST PRIMARY KEY (ID_COMPATIBILIDAD),
CONSTRAINT FK_COMP_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
    CONSTRAINT FK_COMP_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA)
);

CREATE TABLE MATRICULA_PRACTICA (

    ID_MATRICULA_PRACTICA NUMBER(10) NOT NULL,
    ID_ESTUDIANTE NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10),
    ID_PRACTICA NUMBER(10) NOT NULL,
    ID_GRUPO NUMBER(10),
    ID_INSTITUCION NUMBER(10),
    FECHA_MATRICULA DATE DEFAULT SYSDATE NOT NULL,
    ESTADO VARCHAR2(30) DEFAULT 'ACTIVO' NOT NULL,
    ETAPA_ACADEMICA VARCHAR2(30) DEFAULT 'ELECTIVA' NOT NULL,
    HORAS_COMPLETAS NUMBER(1) DEFAULT 0,
    CONSTRAINT PK_MAT_PRAC PRIMARY KEY (ID_MATRICULA_PRACTICA),
CONSTRAINT FK_MP_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_MP_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_MP_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA),
    CONSTRAINT FK_MP_GRUPO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID_GRUPO),
    CONSTRAINT FK_MP_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION)
);

CREATE TABLE ASIGNACION_DOCENTE (

    ID_ASIGNACION_DOCENTE NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10) NOT NULL,
    ID_DOCENTE NUMBER(10),
    ID_GRUPO NUMBER(10),
    ID_PRACTICA NUMBER(10),
    FECHA_ASIGNACION DATE DEFAULT SYSDATE NOT NULL,
    ROL_EN_PRACTICA VARCHAR2(80),
    ID_GRUPO_PRACTICA NUMBER(10),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_ASIG_DOC PRIMARY KEY (ID_ASIGNACION_DOCENTE),
CONSTRAINT FK_AD_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_AD_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_AD_GRUPO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID_GRUPO),
    CONSTRAINT FK_AD_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA)
);

CREATE TABLE RUBRICA (

    ID_RUBRICA NUMBER(10) NOT NULL,
    ID_PRACTICA NUMBER(10),
    ID_DOCENTE NUMBER(10),
    NOMBRE VARCHAR2(150) NOT NULL,
    DESCRIPCION VARCHAR2(1000),
    PONDERACION VARCHAR2(20),
    PUNTAJE_TOTAL NUMBER(6,2) DEFAULT 100,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_RUBRICA PRIMARY KEY (ID_RUBRICA),
CONSTRAINT FK_RUBRICA_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA),
    CONSTRAINT FK_RUBRICA_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CRITERIO_RUBRICA (

    ID_CRITERIO NUMBER(10) NOT NULL,
    ID_RUBRICA NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(150) NOT NULL,
    DESCRIPCION VARCHAR2(1000),
    PONDERACION VARCHAR2(20),
    PUNTAJE_MAXIMO NUMBER(6,2),
    PESO_PORCENTAJE NUMBER(6,2),
    ORDEN NUMBER(3),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_CRIT_RUB PRIMARY KEY (ID_CRITERIO),
CONSTRAINT FK_CRITERIO_RUBRICA FOREIGN KEY (ID_RUBRICA) REFERENCES RUBRICA(ID_RUBRICA)
);

CREATE TABLE NIVEL_DESEMPENO (

    ID_NIVEL NUMBER(10) NOT NULL,
    ID_CRITERIO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    VALOR_MINIMO NUMBER(6,2),
    VALOR_MAXIMO NUMBER(6,2),
    PUNTAJE_MINIMO NUMBER(6,2),
    PUNTAJE_MAXIMO NUMBER(6,2),
    DESCRIPCION VARCHAR2(1000),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_NIVEL_DES PRIMARY KEY (ID_NIVEL),
CONSTRAINT FK_NIVEL_CRITERIO FOREIGN KEY (ID_CRITERIO) REFERENCES CRITERIO_RUBRICA(ID_CRITERIO)
);

CREATE TABLE EVALUACION (

    ID_EVALUACION NUMBER(10) NOT NULL,
    ID_MATRICULA_PRACTICA NUMBER(10),
    ID_PRACTICA NUMBER(10),
    ID_RUBRICA NUMBER(10),
    ID_EVALUADOR NUMBER(10),
    ID_EVALUACION_PROM NUMBER(10),
    NOTA_EVALUACION NUMBER(6,2),
    PUNTAJE_OBTENIDO NUMBER(6,2),
    CRITERIA_LOGRO VARCHAR2(200),
    OBSERVACIONES VARCHAR2(1000),
    FECHA_EVALUACION DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'REGISTRADA' NOT NULL,
    CONSTRAINT PK_EVALUACION PRIMARY KEY (ID_EVALUACION),
CONSTRAINT FK_EVAL_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA),
    CONSTRAINT FK_EVAL_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA),
    CONSTRAINT FK_EVAL_RUBRICA FOREIGN KEY (ID_RUBRICA) REFERENCES RUBRICA(ID_RUBRICA),
    CONSTRAINT FK_EVAL_EVALUADOR FOREIGN KEY (ID_EVALUADOR) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PREGUNTA (

    ID_PREGUNTA NUMBER(10) NOT NULL,
    ID_EVALUACION NUMBER(10),
    ID_PRACTICA NUMBER(10),
    ENUNCIADO VARCHAR2(1000),
    TEXTO_PREGUNTA VARCHAR2(1000),
    TIPO_PREGUNTA VARCHAR2(50),
    PUNTAJE_MAXIMO NUMBER(6,2),
    ID_SUB_TEMA NUMBER(10),
    ORDEN NUMBER(3),
    COMPARTIDA NUMBER(1) DEFAULT 0,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_PREGUNTA PRIMARY KEY (ID_PREGUNTA),
CONSTRAINT FK_PREGUNTA_EVALUACION FOREIGN KEY (ID_EVALUACION) REFERENCES EVALUACION(ID_EVALUACION),
    CONSTRAINT FK_PREGUNTA_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA)
);

CREATE TABLE RESPUESTA (

    ID_RESPUESTA NUMBER(10) NOT NULL,
    ID_PREGUNTA NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10),
    ID_ESTUDIANTE NUMBER(10),
    CONTENIDO_RESPUESTA VARCHAR2(1000),
    RESPUESTA VARCHAR2(1000),
    RETROALIMENTACION VARCHAR2(1000),
    FECHA_RESPUESTA DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'ENVIADA' NOT NULL,
    CONSTRAINT PK_RESPUESTA PRIMARY KEY (ID_RESPUESTA),
CONSTRAINT FK_RESP_PREGUNTA FOREIGN KEY (ID_PREGUNTA) REFERENCES PREGUNTA(ID_PREGUNTA),
    CONSTRAINT FK_RESP_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_RESP_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE REGISTRO_ACTIVIDAD (

    ID_REGISTRO NUMBER(10) NOT NULL,
    ID_ACTIVIDAD NUMBER(10),
    ID_MATRICULA_PRACTICA NUMBER(10),
    ID_USUARIO NUMBER(10),
    ID_INSTITUCION NUMBER(10),
    FECHA_ACTIVIDAD DATE DEFAULT SYSDATE NOT NULL,
    DESCRIPCION VARCHAR2(1000),
    HORAS NUMBER(6,2) DEFAULT 0,
    TIPO_ACTIVIDAD VARCHAR2(80),
    EVIDENCIA VARCHAR2(300),
    ID_EVIDENCIA NUMBER(10),
    OBSERVACIONES VARCHAR2(1000),
    ESTADO VARCHAR2(20) DEFAULT 'REGISTRADO' NOT NULL,
    CONSTRAINT PK_REG_ACT PRIMARY KEY (ID_REGISTRO),
CONSTRAINT FK_RA_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA),
    CONSTRAINT FK_RA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_RA_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION)
);

CREATE TABLE ACTIVIDAD_ESTUDIANTE (

    ID_ACTIVIDAD_ESTUDIANTE NUMBER(10) NOT NULL,
    ID_MATRICULA_PRACTICA NUMBER(10) NOT NULL,
    TITULO VARCHAR2(150),
    DESCRIPCION VARCHAR2(1000),
    FECHA_ACTIVIDAD DATE DEFAULT SYSDATE,
    HORAS_REPORTADAS NUMBER(6,2),
    ESTADO VARCHAR2(20) DEFAULT 'REGISTRADA' NOT NULL,
    CONSTRAINT PK_ACT_EST PRIMARY KEY (ID_ACTIVIDAD_ESTUDIANTE),
CONSTRAINT FK_ACT_EST_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA)
);

CREATE TABLE HORAS_PRACTICA (

    ID_HORAS_PRACTICA NUMBER(10) NOT NULL,
    ID_MATRICULA_PRACTICA NUMBER(10) NOT NULL,
    HORAS_REPORTADAS NUMBER(6,2) DEFAULT 0,
    HORAS_APROBADAS NUMBER(6,2) DEFAULT 0,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    CONFIRMADO_POR_INSTITUCION NUMBER(1) DEFAULT 0,
    ID_SUPERVISOR_INSTITUCION NUMBER(10),
    OBSERVACION VARCHAR2(1000),
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    CONSTRAINT PK_HORAS_PRAC PRIMARY KEY (ID_HORAS_PRACTICA),
CONSTRAINT FK_HP_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA),
    CONSTRAINT FK_HP_SUP FOREIGN KEY (ID_SUPERVISOR_INSTITUCION) REFERENCES SUPERVISOR_INSTITUCION(ID_SUPERVISOR_INSTITUCION)
);

CREATE TABLE DOCUMENTO_ESTUDIANTE (

    ID_DOCUMENTO_ESTUDIANTE NUMBER(10) NOT NULL,
    ID_MATRICULA_PRACTICA NUMBER(10) NOT NULL,
    ID_USUARIO_SUBE NUMBER(10),
    TIPO_DOCUMENTO VARCHAR2(80),
    NOMBRE_ARCHIVO VARCHAR2(255),
    RUTA_ARCHIVO VARCHAR2(500),
    HASH_ARCHIVO VARCHAR2(128),
    FECHA_SUBIDA DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'CARGADO' NOT NULL,
    CONSTRAINT PK_DOC_EST PRIMARY KEY (ID_DOCUMENTO_ESTUDIANTE),
CONSTRAINT FK_DOC_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA),
    CONSTRAINT FK_DOC_USUARIO FOREIGN KEY (ID_USUARIO_SUBE) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE HISTORIAL_REVISION (

    ID_HISTORIAL_REVISION NUMBER(10) NOT NULL,
    ID_MATRICULA_PRACTICA NUMBER(10) NOT NULL,
    ID_USUARIO_REVISA NUMBER(10),
    TIPO_REVISION VARCHAR2(80),
    ESTADO_ANTERIOR VARCHAR2(40),
    ESTADO_NUEVO VARCHAR2(40),
    OBSERVACION VARCHAR2(1000),
    FECHA_REVISION DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_HIST_REV PRIMARY KEY (ID_HISTORIAL_REVISION),
CONSTRAINT FK_HR_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA),
    CONSTRAINT FK_HR_USUARIO FOREIGN KEY (ID_USUARIO_REVISA) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CERTIFICADO_PRACTICA (

    ID_CERTIFICADO_PRACTICA NUMBER(10) NOT NULL,
    ID_MATRICULA_PRACTICA NUMBER(10) NOT NULL,
    ID_USUARIO_EMITE NUMBER(10),
    FECHA_EMISION DATE DEFAULT SYSDATE,
    HASH_VERIFICACION VARCHAR2(128),
    FIRMA_DIGITAL_SIMULADA VARCHAR2(500),
    RUTA_PDF VARCHAR2(500),
    ESTADO VARCHAR2(20) DEFAULT 'EMITIDO' NOT NULL,
    CONSTRAINT PK_CERT_PRAC PRIMARY KEY (ID_CERTIFICADO_PRACTICA),
CONSTRAINT FK_CERT_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA),
    CONSTRAINT FK_CERT_USUARIO FOREIGN KEY (ID_USUARIO_EMITE) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE FORMULARIO_CONTRATO (

    ID_FORMULARIO_CONTRATO NUMBER(10) NOT NULL,
    ID_MATRICULA_PRACTICA NUMBER(10),
    NUMERO_CONTRATO VARCHAR2(60),
    FECHA_GENERACION DATE DEFAULT SYSDATE,
    RUTA_DOCUMENTO VARCHAR2(500),
    ESTADO VARCHAR2(20) DEFAULT 'GENERADO' NOT NULL,
    CONSTRAINT PK_FORM_CONT PRIMARY KEY (ID_FORMULARIO_CONTRATO),
CONSTRAINT FK_FORM_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA)
);

CREATE TABLE NOTIFICACION (

    ID_NOTIFICACION NUMBER(10) NOT NULL,
    ID_USUARIO_DESTINO NUMBER(10),
    TITULO VARCHAR2(150),
    MENSAJE VARCHAR2(1000),
    FECHA_ENVIO DATE DEFAULT SYSDATE,
    LEIDA NUMBER(1) DEFAULT 0,
    TIPO VARCHAR2(50),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVA' NOT NULL,
    CONSTRAINT PK_NOTIFICACION PRIMARY KEY (ID_NOTIFICACION),
CONSTRAINT FK_NOTIF_USUARIO FOREIGN KEY (ID_USUARIO_DESTINO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE MENSAJE_INTERNO (

    ID_MENSAJE_INTERNO NUMBER(10) NOT NULL,
    ID_USUARIO_ORIGEN NUMBER(10),
    ID_USUARIO_DESTINO NUMBER(10),
    ASUNTO VARCHAR2(150),
    MENSAJE VARCHAR2(1000),
    FECHA_ENVIO DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'ENVIADO' NOT NULL,
    CONSTRAINT PK_MSG_INT PRIMARY KEY (ID_MENSAJE_INTERNO),
CONSTRAINT FK_MSG_ORIGEN FOREIGN KEY (ID_USUARIO_ORIGEN) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_MSG_DESTINO FOREIGN KEY (ID_USUARIO_DESTINO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE RESPUESTA_RAPIDA_DOCENTE (

    ID_RESPUESTA_RAPIDA NUMBER(10) NOT NULL,
    ID_DOCENTE NUMBER(10),
    TITULO VARCHAR2(120),
    TEXTO VARCHAR2(1000),
    FECHA_CREACION DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_RESP_RAP PRIMARY KEY (ID_RESPUESTA_RAPIDA),
CONSTRAINT FK_RR_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE REPORTE (

    ID_REPORTE NUMBER(10) NOT NULL,
    ID_USUARIO_GENERA NUMBER(10),
    TITULO VARCHAR2(150),
    NOMBRE VARCHAR2(150),
    DESCRIPCION VARCHAR2(1000),
    COMENTARIOS VARCHAR2(1000),
    TIPO_REPORTE VARCHAR2(80),
    FECHA DATE DEFAULT SYSDATE,
    FECHA_GENERACION DATE DEFAULT SYSDATE,
    RUTA_ARCHIVO VARCHAR2(500),
    HASH_VERIFICACION VARCHAR2(128),
    ESTADO VARCHAR2(20) DEFAULT 'GENERADO' NOT NULL,
    CONSTRAINT PK_REPORTE PRIMARY KEY (ID_REPORTE),
CONSTRAINT FK_REPORTE_USUARIO FOREIGN KEY (ID_USUARIO_GENERA) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE SERVICIOS (

    ID_SERVICIO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(120) NOT NULL,
    DESCRIPCION VARCHAR2(1000),
    URL_SERVICIO VARCHAR2(300),
    ACTIVO NUMBER(1) DEFAULT 1,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_SERVICIOS PRIMARY KEY (ID_SERVICIO)
);

CREATE TABLE CONFIGURACION_GLOBAL (

    ID_CONFIGURACION_GLOBAL NUMBER(10) NOT NULL,
    CLAVE VARCHAR2(120) NOT NULL,
    VALOR VARCHAR2(1000),
    DESCRIPCION VARCHAR2(1000),
    FECHA_ACTUALIZACION DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_CONF_GLOB PRIMARY KEY (ID_CONFIGURACION_GLOBAL),
CONSTRAINT UK_CONFIG_CLAVE UNIQUE (CLAVE)
);

CREATE TABLE LOG_ACTIVIDAD (

    ID_LOG NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10),
    TABLA_AFECTADA VARCHAR2(80),
    TABLA VARCHAR2(80),
    ID_REGISTRO VARCHAR2(80),
    TIPO_OPERACION VARCHAR2(30),
    ACCION VARCHAR2(40),
    VALOR_ANTERIOR CLOB,
    VALOR_NUEVO CLOB,
    MODULO VARCHAR2(80),
    IP_EQUIPO VARCHAR2(80),
    USUARIO_BD VARCHAR2(80) DEFAULT USER,
    FECHA_HORA DATE DEFAULT SYSDATE,
    FECHA_LOG DATE DEFAULT SYSDATE,
    CONSTRAINT PK_LOG_ACT PRIMARY KEY (ID_LOG),
CONSTRAINT FK_LOG_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE LOGIN_AUDITORIA (

    ID_LOGIN_AUDITORIA NUMBER(10) NOT NULL,
    ID_USUARIO NUMBER(10),
    CORREO VARCHAR2(120),
    FECHA_LOGIN DATE DEFAULT SYSDATE,
    EXITO NUMBER(1),
    IP_EQUIPO VARCHAR2(80),
    MENSAJE VARCHAR2(500),
    CONSTRAINT PK_LOGIN_AUD PRIMARY KEY (ID_LOGIN_AUDITORIA),
CONSTRAINT FK_LOGIN_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE SEQUENCE SEQ_ROL START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_USUARIO START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_PROGRAMA START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_CURSO START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_INSTITUCION START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_PRACTICA START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_GRUPO START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_CONV_INST START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_SUP_INST START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_OFERTA_PRAC START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_COMP_INST START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_MAT_PRAC START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_ASIG_DOC START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_RUBRICA START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_CRIT_RUB START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_NIVEL_DES START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_EVALUACION START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_PREGUNTA START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_RESPUESTA START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_REG_ACT START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_ACT_EST START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_HORAS_PRAC START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_DOC_EST START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_HIST_REV START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_CERT_PRAC START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_FORM_CONT START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_NOTIFICACION START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_MSG_INT START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_RESP_RAP START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_REPORTE START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_SERVICIOS START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_CONF_GLOB START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_LOG_ACT START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE SEQ_LOGIN_AUD START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER BI_ROL
BEFORE INSERT ON ROL
FOR EACH ROW
BEGIN
    IF :NEW.ID_ROL IS NULL THEN
        SELECT SEQ_ROL.NEXTVAL INTO :NEW.ID_ROL FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_USUARIO
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_USUARIO IS NULL THEN
        SELECT SEQ_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_PROGRAMA
BEFORE INSERT ON PROGRAMA
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROGRAMA IS NULL THEN
        SELECT SEQ_PROGRAMA.NEXTVAL INTO :NEW.ID_PROGRAMA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_CURSO
BEFORE INSERT ON CURSO
FOR EACH ROW
BEGIN
    IF :NEW.ID_CURSO IS NULL THEN
        SELECT SEQ_CURSO.NEXTVAL INTO :NEW.ID_CURSO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_INSTITUCION
BEFORE INSERT ON INSTITUCION
FOR EACH ROW
BEGIN
    IF :NEW.ID_INSTITUCION IS NULL THEN
        SELECT SEQ_INSTITUCION.NEXTVAL INTO :NEW.ID_INSTITUCION FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_PRACTICA
BEFORE INSERT ON PRACTICA
FOR EACH ROW
BEGIN
    IF :NEW.ID_PRACTICA IS NULL THEN
        SELECT SEQ_PRACTICA.NEXTVAL INTO :NEW.ID_PRACTICA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_GRUPO
BEFORE INSERT ON GRUPO
FOR EACH ROW
BEGIN
    IF :NEW.ID_GRUPO IS NULL THEN
        SELECT SEQ_GRUPO.NEXTVAL INTO :NEW.ID_GRUPO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_CONV_INST
BEFORE INSERT ON CONVENIO_INSTITUCION
FOR EACH ROW
BEGIN
    IF :NEW.ID_CONVENIO_INSTITUCION IS NULL THEN
        SELECT SEQ_CONV_INST.NEXTVAL INTO :NEW.ID_CONVENIO_INSTITUCION FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_SUP_INST
BEFORE INSERT ON SUPERVISOR_INSTITUCION
FOR EACH ROW
BEGIN
    IF :NEW.ID_SUPERVISOR_INSTITUCION IS NULL THEN
        SELECT SEQ_SUP_INST.NEXTVAL INTO :NEW.ID_SUPERVISOR_INSTITUCION FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_OFERTA_PRAC
BEFORE INSERT ON OFERTA_PRACTICA
FOR EACH ROW
BEGIN
    IF :NEW.ID_OFERTA_PRACTICA IS NULL THEN
        SELECT SEQ_OFERTA_PRAC.NEXTVAL INTO :NEW.ID_OFERTA_PRACTICA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_COMP_INST
BEFORE INSERT ON COMPATIBILIDAD_INSTITUCION
FOR EACH ROW
BEGIN
    IF :NEW.ID_COMPATIBILIDAD IS NULL THEN
        SELECT SEQ_COMP_INST.NEXTVAL INTO :NEW.ID_COMPATIBILIDAD FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_MAT_PRAC
BEFORE INSERT ON MATRICULA_PRACTICA
FOR EACH ROW
BEGIN
    IF :NEW.ID_MATRICULA_PRACTICA IS NULL THEN
        SELECT SEQ_MAT_PRAC.NEXTVAL INTO :NEW.ID_MATRICULA_PRACTICA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_ASIG_DOC
BEFORE INSERT ON ASIGNACION_DOCENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_ASIGNACION_DOCENTE IS NULL THEN
        SELECT SEQ_ASIG_DOC.NEXTVAL INTO :NEW.ID_ASIGNACION_DOCENTE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_RUBRICA
BEFORE INSERT ON RUBRICA
FOR EACH ROW
BEGIN
    IF :NEW.ID_RUBRICA IS NULL THEN
        SELECT SEQ_RUBRICA.NEXTVAL INTO :NEW.ID_RUBRICA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_CRIT_RUB
BEFORE INSERT ON CRITERIO_RUBRICA
FOR EACH ROW
BEGIN
    IF :NEW.ID_CRITERIO IS NULL THEN
        SELECT SEQ_CRIT_RUB.NEXTVAL INTO :NEW.ID_CRITERIO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_NIVEL_DES
BEFORE INSERT ON NIVEL_DESEMPENO
FOR EACH ROW
BEGIN
    IF :NEW.ID_NIVEL IS NULL THEN
        SELECT SEQ_NIVEL_DES.NEXTVAL INTO :NEW.ID_NIVEL FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_EVALUACION
BEFORE INSERT ON EVALUACION
FOR EACH ROW
BEGIN
    IF :NEW.ID_EVALUACION IS NULL THEN
        SELECT SEQ_EVALUACION.NEXTVAL INTO :NEW.ID_EVALUACION FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_PREGUNTA
BEFORE INSERT ON PREGUNTA
FOR EACH ROW
BEGIN
    IF :NEW.ID_PREGUNTA IS NULL THEN
        SELECT SEQ_PREGUNTA.NEXTVAL INTO :NEW.ID_PREGUNTA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_RESPUESTA
BEFORE INSERT ON RESPUESTA
FOR EACH ROW
BEGIN
    IF :NEW.ID_RESPUESTA IS NULL THEN
        SELECT SEQ_RESPUESTA.NEXTVAL INTO :NEW.ID_RESPUESTA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_REG_ACT
BEFORE INSERT ON REGISTRO_ACTIVIDAD
FOR EACH ROW
BEGIN
    IF :NEW.ID_REGISTRO IS NULL THEN
        SELECT SEQ_REG_ACT.NEXTVAL INTO :NEW.ID_REGISTRO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_ACT_EST
BEFORE INSERT ON ACTIVIDAD_ESTUDIANTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_ACTIVIDAD_ESTUDIANTE IS NULL THEN
        SELECT SEQ_ACT_EST.NEXTVAL INTO :NEW.ID_ACTIVIDAD_ESTUDIANTE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_HORAS_PRAC
BEFORE INSERT ON HORAS_PRACTICA
FOR EACH ROW
BEGIN
    IF :NEW.ID_HORAS_PRACTICA IS NULL THEN
        SELECT SEQ_HORAS_PRAC.NEXTVAL INTO :NEW.ID_HORAS_PRACTICA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_DOC_EST
BEFORE INSERT ON DOCUMENTO_ESTUDIANTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_DOCUMENTO_ESTUDIANTE IS NULL THEN
        SELECT SEQ_DOC_EST.NEXTVAL INTO :NEW.ID_DOCUMENTO_ESTUDIANTE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_HIST_REV
BEFORE INSERT ON HISTORIAL_REVISION
FOR EACH ROW
BEGIN
    IF :NEW.ID_HISTORIAL_REVISION IS NULL THEN
        SELECT SEQ_HIST_REV.NEXTVAL INTO :NEW.ID_HISTORIAL_REVISION FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_CERT_PRAC
BEFORE INSERT ON CERTIFICADO_PRACTICA
FOR EACH ROW
BEGIN
    IF :NEW.ID_CERTIFICADO_PRACTICA IS NULL THEN
        SELECT SEQ_CERT_PRAC.NEXTVAL INTO :NEW.ID_CERTIFICADO_PRACTICA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_FORM_CONT
BEFORE INSERT ON FORMULARIO_CONTRATO
FOR EACH ROW
BEGIN
    IF :NEW.ID_FORMULARIO_CONTRATO IS NULL THEN
        SELECT SEQ_FORM_CONT.NEXTVAL INTO :NEW.ID_FORMULARIO_CONTRATO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_NOTIFICACION
BEFORE INSERT ON NOTIFICACION
FOR EACH ROW
BEGIN
    IF :NEW.ID_NOTIFICACION IS NULL THEN
        SELECT SEQ_NOTIFICACION.NEXTVAL INTO :NEW.ID_NOTIFICACION FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_MSG_INT
BEFORE INSERT ON MENSAJE_INTERNO
FOR EACH ROW
BEGIN
    IF :NEW.ID_MENSAJE_INTERNO IS NULL THEN
        SELECT SEQ_MSG_INT.NEXTVAL INTO :NEW.ID_MENSAJE_INTERNO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_RESP_RAP
BEFORE INSERT ON RESPUESTA_RAPIDA_DOCENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_RESPUESTA_RAPIDA IS NULL THEN
        SELECT SEQ_RESP_RAP.NEXTVAL INTO :NEW.ID_RESPUESTA_RAPIDA FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_REPORTE
BEFORE INSERT ON REPORTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_REPORTE IS NULL THEN
        SELECT SEQ_REPORTE.NEXTVAL INTO :NEW.ID_REPORTE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_SERVICIOS
BEFORE INSERT ON SERVICIOS
FOR EACH ROW
BEGIN
    IF :NEW.ID_SERVICIO IS NULL THEN
        SELECT SEQ_SERVICIOS.NEXTVAL INTO :NEW.ID_SERVICIO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_CONF_GLOB
BEFORE INSERT ON CONFIGURACION_GLOBAL
FOR EACH ROW
BEGIN
    IF :NEW.ID_CONFIGURACION_GLOBAL IS NULL THEN
        SELECT SEQ_CONF_GLOB.NEXTVAL INTO :NEW.ID_CONFIGURACION_GLOBAL FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_LOG_ACT
BEFORE INSERT ON LOG_ACTIVIDAD
FOR EACH ROW
BEGIN
    IF :NEW.ID_LOG IS NULL THEN
        SELECT SEQ_LOG_ACT.NEXTVAL INTO :NEW.ID_LOG FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_LOGIN_AUD
BEFORE INSERT ON LOGIN_AUDITORIA
FOR EACH ROW
BEGIN
    IF :NEW.ID_LOGIN_AUDITORIA IS NULL THEN
        SELECT SEQ_LOGIN_AUD.NEXTVAL INTO :NEW.ID_LOGIN_AUDITORIA FROM DUAL;
    END IF;
END;
/


CREATE INDEX IDX_USUARIO_ROL_TXT ON USUARIO(ROL);
CREATE INDEX IDX_USUARIO_TIPO ON USUARIO(TIPO_USUARIO);
CREATE INDEX IDX_PRACTICA_ESTADO ON PRACTICA(ESTADO);
CREATE INDEX IDX_MP_ESTUDIANTE ON MATRICULA_PRACTICA(ID_ESTUDIANTE);
CREATE INDEX IDX_MP_PRACTICA ON MATRICULA_PRACTICA(ID_PRACTICA);
CREATE INDEX IDX_RA_MP ON REGISTRO_ACTIVIDAD(ID_MATRICULA_PRACTICA);
CREATE INDEX IDX_DOC_MP ON DOCUMENTO_ESTUDIANTE(ID_MATRICULA_PRACTICA);
CREATE INDEX IDX_LOG_TABLA ON LOG_ACTIVIDAD(TABLA_AFECTADA);


CREATE OR REPLACE VIEW VW_PRACTICAS_ACTIVAS AS
SELECT P.ID_PRACTICA, P.NOMBRE, NVL(P.TITULO, P.NOMBRE) TITULO, P.PERIODO_ACADEMICO,
       P.HORAS_REGLAMENTARIAS, P.ESTADO, PR.NOMBRE AS PROGRAMA
FROM PRACTICA P
LEFT JOIN PROGRAMA PR ON P.ID_PROGRAMA = PR.ID_PROGRAMA
WHERE NVL(UPPER(P.ESTADO),'ACTIVO') IN ('ACTIVO','EN CURSO','PENDIENTE','PLANIFICADA');
/

CREATE OR REPLACE VIEW VW_HORAS_ESTUDIANTE AS
SELECT U.ID_USUARIO AS ID_ESTUDIANTE,
       U.NOMBRE || ' ' || U.APELLIDO AS ESTUDIANTE,
       M.ID_MATRICULA_PRACTICA,
       P.NOMBRE AS PRACTICA,
       NVL(SUM(R.HORAS),0) AS HORAS_REGISTRADAS,
       NVL(MAX(P.HORAS_REGLAMENTARIAS),0) AS HORAS_REQUERIDAS,
       CASE WHEN NVL(SUM(R.HORAS),0) >= NVL(MAX(P.HORAS_REGLAMENTARIAS),0) THEN 'CUMPLE' ELSE 'PENDIENTE' END AS ESTADO_HORAS
FROM USUARIO U
JOIN MATRICULA_PRACTICA M ON U.ID_USUARIO = M.ID_ESTUDIANTE
JOIN PRACTICA P ON M.ID_PRACTICA = P.ID_PRACTICA
LEFT JOIN REGISTRO_ACTIVIDAD R ON M.ID_MATRICULA_PRACTICA = R.ID_MATRICULA_PRACTICA
GROUP BY U.ID_USUARIO, U.NOMBRE, U.APELLIDO, M.ID_MATRICULA_PRACTICA, P.NOMBRE;
/

CREATE OR REPLACE VIEW VW_ESTUDIANTES_MATRICULADOS AS
SELECT M.ID_MATRICULA_PRACTICA, U.ID_USUARIO AS ID_ESTUDIANTE,
       U.NOMBRE || ' ' || U.APELLIDO AS ESTUDIANTE, U.EMAIL,
       P.NOMBRE AS PRACTICA, G.NOMBRE AS GRUPO, I.NOMBRE AS INSTITUCION,
       M.FECHA_MATRICULA, M.ESTADO, M.ETAPA_ACADEMICA
FROM MATRICULA_PRACTICA M
JOIN USUARIO U ON M.ID_ESTUDIANTE = U.ID_USUARIO
JOIN PRACTICA P ON M.ID_PRACTICA = P.ID_PRACTICA
LEFT JOIN GRUPO G ON M.ID_GRUPO = G.ID_GRUPO
LEFT JOIN INSTITUCION I ON M.ID_INSTITUCION = I.ID_INSTITUCION;
/

CREATE OR REPLACE VIEW VW_EVALUACIONES_COMPLETAS AS
SELECT E.ID_EVALUACION, M.ID_MATRICULA_PRACTICA, U.NOMBRE || ' ' || U.APELLIDO AS ESTUDIANTE,
       P.NOMBRE AS PRACTICA, R.NOMBRE AS RUBRICA,
       NVL(E.NOTA_EVALUACION, E.PUNTAJE_OBTENIDO) AS NOTA,
       E.OBSERVACIONES, E.FECHA_EVALUACION, E.ESTADO
FROM EVALUACION E
JOIN MATRICULA_PRACTICA M ON E.ID_MATRICULA_PRACTICA = M.ID_MATRICULA_PRACTICA
JOIN USUARIO U ON M.ID_ESTUDIANTE = U.ID_USUARIO
LEFT JOIN PRACTICA P ON M.ID_PRACTICA = P.ID_PRACTICA
LEFT JOIN RUBRICA R ON E.ID_RUBRICA = R.ID_RUBRICA;
/

CREATE OR REPLACE VIEW VW_PRACTICAS_INSTITUCION AS
SELECT I.ID_INSTITUCION, I.NOMBRE AS INSTITUCION, P.ID_PRACTICA, P.NOMBRE AS PRACTICA,
       COUNT(M.ID_MATRICULA_PRACTICA) AS ESTUDIANTES_ASIGNADOS,
       P.ESTADO
FROM INSTITUCION I
LEFT JOIN MATRICULA_PRACTICA M ON I.ID_INSTITUCION = M.ID_INSTITUCION
LEFT JOIN PRACTICA P ON M.ID_PRACTICA = P.ID_PRACTICA
GROUP BY I.ID_INSTITUCION, I.NOMBRE, P.ID_PRACTICA, P.NOMBRE, P.ESTADO;
/

COMMIT;
PROMPT Esquema completo creado correctamente.
