-- =============================================================
-- Roles y privilegios Oracle sugeridos para despliegue.
-- Ejecutar como DBA o usuario administrador del esquema.
-- Ajuste PROYECTOJD por el nombre real del esquema si cambia.
-- =============================================================

CREATE ROLE ROL_GP_DIRECTOR;
CREATE ROLE ROL_GP_COORDINADOR;
CREATE ROLE ROL_GP_DOCENTE;
CREATE ROLE ROL_GP_ESTUDIANTE;
CREATE ROLE ROL_GP_INSTITUCION;

GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIO TO ROL_GP_DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROL TO ROL_GP_DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRACTICA TO ROL_GP_DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON INSTITUCION TO ROL_GP_DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON MATRICULA_PRACTICA TO ROL_GP_DIRECTOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUACION TO ROL_GP_DIRECTOR;
GRANT SELECT, INSERT, UPDATE ON REPORTE TO ROL_GP_DIRECTOR;
GRANT SELECT ON LOG_ACTIVIDAD TO ROL_GP_DIRECTOR;
GRANT SELECT ON HISTORIAL_REVISION TO ROL_GP_DIRECTOR;

GRANT SELECT, INSERT, UPDATE ON GRUPO TO ROL_GP_COORDINADOR;
GRANT SELECT, INSERT, UPDATE ON MATRICULA_PRACTICA TO ROL_GP_COORDINADOR;
GRANT SELECT, INSERT, UPDATE ON CONVENIO_INSTITUCION TO ROL_GP_COORDINADOR;
GRANT SELECT, INSERT, UPDATE ON HORAS_PRACTICA TO ROL_GP_COORDINADOR;
GRANT SELECT, INSERT ON HISTORIAL_REVISION TO ROL_GP_COORDINADOR;

GRANT SELECT, INSERT, UPDATE ON EVALUACION TO ROL_GP_DOCENTE;
GRANT SELECT, INSERT, UPDATE ON RUBRICA TO ROL_GP_DOCENTE;
GRANT SELECT, INSERT, UPDATE ON CRITERIO_RUBRICA TO ROL_GP_DOCENTE;
GRANT SELECT, INSERT, UPDATE ON PREGUNTA TO ROL_GP_DOCENTE;
GRANT SELECT, UPDATE ON RESPUESTA TO ROL_GP_DOCENTE;
GRANT SELECT ON MATRICULA_PRACTICA TO ROL_GP_DOCENTE;

GRANT SELECT, INSERT, UPDATE ON REGISTRO_ACTIVIDAD TO ROL_GP_ESTUDIANTE;
GRANT SELECT, INSERT ON DOCUMENTO_ESTUDIANTE TO ROL_GP_ESTUDIANTE;
GRANT SELECT, INSERT ON RESPUESTA TO ROL_GP_ESTUDIANTE;
GRANT SELECT ON EVALUACION TO ROL_GP_ESTUDIANTE;
GRANT SELECT ON CERTIFICADO_PRACTICA TO ROL_GP_ESTUDIANTE;

GRANT SELECT, UPDATE ON HORAS_PRACTICA TO ROL_GP_INSTITUCION;
GRANT SELECT ON MATRICULA_PRACTICA TO ROL_GP_INSTITUCION;
GRANT SELECT ON CONVENIO_INSTITUCION TO ROL_GP_INSTITUCION;

-- Ejemplo de asignación:
-- GRANT ROL_GP_DIRECTOR TO PROYECTOJD;
-- ALTER USER PROYECTOJD DEFAULT ROLE ROL_GP_DIRECTOR;
