-- Consultas rápidas de validación funcional
SELECT COUNT(*) AS TOTAL_USUARIOS FROM USUARIO;
SELECT * FROM VW_ESTUDIANTES_MATRICULADOS;
SELECT * FROM VW_HORAS_ESTUDIANTE;
SELECT FN_TOTAL_HORAS_ESTUDIANTE(4) AS HORAS_JUAN FROM DUAL;
SELECT FN_ESTADO_HORAS(1) AS ESTADO_HORAS_MATRICULA_1 FROM DUAL;
SELECT * FROM LOG_ACTIVIDAD ORDER BY FECHA_HORA DESC;
