-- Patch v1.3 para presentación: columnas usadas por las pantallas simplificadas.
-- Ejecutar conectado como PROYECTOJD si alguna tabla/columna no existe.
SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE ADD_COL_IF_MISSING(p_table VARCHAR2, p_col VARCHAR2, p_def VARCHAR2) AS
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = UPPER(p_table) AND COLUMN_NAME = UPPER(p_col);
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_col || ' ' || p_def || ')';
    DBMS_OUTPUT.PUT_LINE('Columna agregada: ' || p_table || '.' || p_col);
  END IF;
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('No se pudo agregar ' || p_table || '.' || p_col || ': ' || SQLERRM);
END;
/

BEGIN
  ADD_COL_IF_MISSING('HORAS_PRACTICA','HORAS_REPORTADAS','NUMBER(6,2) DEFAULT 0');
  ADD_COL_IF_MISSING('HORAS_PRACTICA','HORAS_APROBADAS','NUMBER(6,2) DEFAULT 0');
  ADD_COL_IF_MISSING('HORAS_PRACTICA','FECHA_REGISTRO','DATE DEFAULT SYSDATE');
  ADD_COL_IF_MISSING('HORAS_PRACTICA','OBSERVACION','VARCHAR2(1000)');
  ADD_COL_IF_MISSING('HORAS_PRACTICA','ESTADO','VARCHAR2(20) DEFAULT ''PENDIENTE''');
  ADD_COL_IF_MISSING('REGISTRO_ACTIVIDAD','ID_MATRICULA_PRACTICA','NUMBER(10)');
  ADD_COL_IF_MISSING('REGISTRO_ACTIVIDAD','HORAS','NUMBER(6,2) DEFAULT 0');
  ADD_COL_IF_MISSING('REGISTRO_ACTIVIDAD','OBSERVACIONES','VARCHAR2(1000)');
  ADD_COL_IF_MISSING('REGISTRO_ACTIVIDAD','ESTADO','VARCHAR2(20) DEFAULT ''PENDIENTE''');
  ADD_COL_IF_MISSING('RESPUESTA','RETROALIMENTACION','VARCHAR2(1000)');
  ADD_COL_IF_MISSING('EVALUACION','OBSERVACIONES','VARCHAR2(1000)');
  ADD_COL_IF_MISSING('EVALUACION','PUNTAJE_OBTENIDO','NUMBER(6,2) DEFAULT 0');
  ADD_COL_IF_MISSING('REPORTE','COMENTARIOS','VARCHAR2(1000)');
  ADD_COL_IF_MISSING('REPORTE','RUTA_ARCHIVO','VARCHAR2(500)');
END;
/
DROP PROCEDURE ADD_COL_IF_MISSING;

COMMIT;
