-- ==========================================================
-- PROYECTOJD - Software para la Gestión de Prácticas Académicas
-- Script de creación de tablas para Oracle 10g
-- Compatible con el código Java Swing / DAO del proyecto.
-- ==========================================================

CREATE TABLE USUARIO (
    ID_USUARIO      NUMBER(10)       NOT NULL,
    NOMBRE          VARCHAR2(80)     NOT NULL,
    APELLIDO        VARCHAR2(80)     NOT NULL,
    EMAIL           VARCHAR2(120)    NOT NULL,
    CONTRASENA      VARCHAR2(120)    NOT NULL,
    TIPO_USUARIO    VARCHAR2(30)     NOT NULL,
    ESTADO          VARCHAR2(20)     DEFAULT 'ACTIVO' NOT NULL,
    TELEFONO        VARCHAR2(30),
    DOCUMENTO       VARCHAR2(30),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USUARIO_TIPO CHECK (TIPO_USUARIO IN ('DIRECTOR','COORDINADOR','DOCENTE','ESTUDIANTE','INSTITUCION')),
    CONSTRAINT CK_USUARIO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE PROGRAMA (
    ID_PROGRAMA          NUMBER(10)      NOT NULL,
    NOMBRE               VARCHAR2(150)   NOT NULL,
    CODIGO               VARCHAR2(30)    NOT NULL,
    DESCRIPCION          VARCHAR2(1000),
    FACULTAD             VARCHAR2(120),
    DURACION_SEMESTRES   NUMBER(2),
    ESTADO               VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_PROGRAMA PRIMARY KEY (ID_PROGRAMA),
    CONSTRAINT UK_PROGRAMA_CODIGO UNIQUE (CODIGO),
    CONSTRAINT CK_PROGRAMA_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE CURSO (
    ID_CURSO       NUMBER(10)      NOT NULL,
    NOMBRE         VARCHAR2(150)   NOT NULL,
    CODIGO         VARCHAR2(30)    NOT NULL,
    CREDITOS       NUMBER(2)       DEFAULT 3,
    ID_PROGRAMA    NUMBER(10)      NOT NULL,
    DESCRIPCION    VARCHAR2(1000),
    ESTADO         VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY (ID_CURSO),
    CONSTRAINT UK_CURSO_CODIGO UNIQUE (CODIGO),
    CONSTRAINT FK_CURSO_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA(ID_PROGRAMA),
    CONSTRAINT CK_CURSO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE GRUPO (
    ID_GRUPO     NUMBER(10)      NOT NULL,
    NOMBRE       VARCHAR2(80)    NOT NULL,
    ID_CURSO     NUMBER(10)      NOT NULL,
    ID_DOCENTE   NUMBER(10)      NOT NULL,
    SEMESTRE     VARCHAR2(20),
    ANIO         NUMBER(4),
    ESTADO       VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_GRUPO PRIMARY KEY (ID_GRUPO),
    CONSTRAINT FK_GRUPO_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    CONSTRAINT FK_GRUPO_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT CK_GRUPO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE INSTITUCION (
    ID_INSTITUCION  NUMBER(10)      NOT NULL,
    NOMBRE          VARCHAR2(150)   NOT NULL,
    DIRECCION       VARCHAR2(200),
    TELEFONO        VARCHAR2(30),
    EMAIL           VARCHAR2(120),
    NIT             VARCHAR2(40),
    CIUDAD          VARCHAR2(80),
    REPRESENTANTE   VARCHAR2(120),
    SITIO_WEB       VARCHAR2(150),
    FECHA_REGISTRO  DATE            DEFAULT SYSDATE,
    ESTADO          VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_INSTITUCION PRIMARY KEY (ID_INSTITUCION),
    CONSTRAINT UK_INSTITUCION_NIT UNIQUE (NIT),
    CONSTRAINT CK_INSTITUCION_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE PRACTICA (
    ID_PRACTICA        NUMBER(10)      NOT NULL,
    TITULO             VARCHAR2(150)   NOT NULL,
    DESCRIPCION        VARCHAR2(1000),
    TIPO_PRACTICA      VARCHAR2(80),
    FECHA_INICIO       DATE,
    FECHA_FIN          DATE,
    ID_INSTITUCION     NUMBER(10),
    ID_CURSO           NUMBER(10),
    ID_GRUPO           NUMBER(10),
    HORAS_REQUERIDAS   NUMBER(5)       DEFAULT 0,
    ESTADO             VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_PRACTICA PRIMARY KEY (ID_PRACTICA),
    CONSTRAINT FK_PRACTICA_INSTITUCION_USR FOREIGN KEY (ID_INSTITUCION) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_PRACTICA_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    CONSTRAINT FK_PRACTICA_GRUPO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID_GRUPO)
);

CREATE TABLE MATRICULA_PRACTICA (
    ID_MATRICULA_PRACTICA NUMBER(10) NOT NULL,
    ID_ESTUDIANTE         NUMBER(10) NOT NULL,
    ID_PRACTICA           NUMBER(10) NOT NULL,
    ID_GRUPO              NUMBER(10) NOT NULL,
    FECHA_MATRICULA       DATE       DEFAULT SYSDATE NOT NULL,
    ESTADO                VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_MATRICULA_PRACTICA PRIMARY KEY (ID_MATRICULA_PRACTICA),
    CONSTRAINT FK_MP_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_MP_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA),
    CONSTRAINT FK_MP_GRUPO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID_GRUPO)
);

CREATE TABLE ASIGNACION_DOCENTE (
    ID_ASIGNACION_DOCENTE NUMBER(10) NOT NULL,
    FECHA_ASIGNACION      DATE       DEFAULT SYSDATE NOT NULL,
    ROL_EN_PRACTICA       VARCHAR2(80),
    ID_PRACTICA           NUMBER(10) NOT NULL,
    ID_USUARIO            NUMBER(10) NOT NULL,
    ESTADO                VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_ASIGNACION_DOCENTE PRIMARY KEY (ID_ASIGNACION_DOCENTE),
    CONSTRAINT FK_AD_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA),
    CONSTRAINT FK_AD_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE RUBRICA (
    ID_RUBRICA      NUMBER(10)      NOT NULL,
    NOMBRE          VARCHAR2(150)   NOT NULL,
    DESCRIPCION     VARCHAR2(1000),
    ID_DOCENTE      NUMBER(10)      NOT NULL,
    ID_PRACTICA     NUMBER(10)      NOT NULL,
    PUNTAJE_TOTAL   NUMBER(6,2)     DEFAULT 100,
    FECHA_CREACION  DATE            DEFAULT SYSDATE,
    ESTADO          VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_RUBRICA PRIMARY KEY (ID_RUBRICA),
    CONSTRAINT FK_RUBRICA_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_RUBRICA_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA)
);

CREATE TABLE CRITERIO_RUBRICA (
    ID_CRITERIO       NUMBER(10)      NOT NULL,
    ID_RUBRICA        NUMBER(10)      NOT NULL,
    NOMBRE            VARCHAR2(150)   NOT NULL,
    DESCRIPCION       VARCHAR2(1000),
    PUNTAJE_MAXIMO    NUMBER(6,2),
    PESO_PORCENTAJE   NUMBER(6,2),
    ORDEN             NUMBER(3),
    ESTADO            VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_CRITERIO_RUBRICA PRIMARY KEY (ID_CRITERIO),
    CONSTRAINT FK_CRITERIO_RUBRICA FOREIGN KEY (ID_RUBRICA) REFERENCES RUBRICA(ID_RUBRICA)
);

CREATE TABLE NIVEL_DESEMPENO (
    ID_NIVEL         NUMBER(10)      NOT NULL,
    ID_CRITERIO      NUMBER(10)      NOT NULL,
    NOMBRE           VARCHAR2(100)   NOT NULL,
    DESCRIPCION      VARCHAR2(1000),
    PUNTAJE_MINIMO   NUMBER(6,2),
    PUNTAJE_MAXIMO   NUMBER(6,2),
    ESTADO           VARCHAR2(20)    DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_NIVEL_DESEMPENO PRIMARY KEY (ID_NIVEL),
    CONSTRAINT FK_NIVEL_CRITERIO FOREIGN KEY (ID_CRITERIO) REFERENCES CRITERIO_RUBRICA(ID_CRITERIO)
);

CREATE TABLE EVALUACION (
    ID_EVALUACION          NUMBER(10)  NOT NULL,
    ID_MATRICULA_PRACTICA  NUMBER(10)  NOT NULL,
    ID_RUBRICA             NUMBER(10)  NOT NULL,
    ID_EVALUADOR           NUMBER(10)  NOT NULL,
    PUNTAJE_OBTENIDO       NUMBER(6,2),
    OBSERVACIONES          VARCHAR2(1000),
    FECHA_EVALUACION       DATE        DEFAULT SYSDATE,
    ESTADO                 VARCHAR2(20) DEFAULT 'REGISTRADA' NOT NULL,
    CONSTRAINT PK_EVALUACION PRIMARY KEY (ID_EVALUACION),
    CONSTRAINT FK_EVAL_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA),
    CONSTRAINT FK_EVAL_RUBRICA FOREIGN KEY (ID_RUBRICA) REFERENCES RUBRICA(ID_RUBRICA),
    CONSTRAINT FK_EVAL_EVALUADOR FOREIGN KEY (ID_EVALUADOR) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PREGUNTA (
    ID_PREGUNTA      NUMBER(10)      NOT NULL,
    TEXTO_PREGUNTA   VARCHAR2(1000)  NOT NULL,
    TIPO_PREGUNTA    VARCHAR2(50),
    PUNTAJE_MAXIMO   NUMBER(6,2),
    ORDEN            NUMBER(3),
    ID_EVALUACION    NUMBER(10),
    ID_PRACTICA      NUMBER(10),
    ESTADO           VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT PK_PREGUNTA PRIMARY KEY (ID_PREGUNTA),
    CONSTRAINT FK_PREGUNTA_EVAL FOREIGN KEY (ID_EVALUACION) REFERENCES EVALUACION(ID_EVALUACION),
    CONSTRAINT FK_PREGUNTA_PRACTICA FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA)
);

CREATE TABLE REGISTRO_ACTIVIDAD (
    ID_REGISTRO            NUMBER(10)      NOT NULL,
    ID_MATRICULA_PRACTICA  NUMBER(10)      NOT NULL,
    FECHA_ACTIVIDAD        DATE            DEFAULT SYSDATE NOT NULL,
    DESCRIPCION            VARCHAR2(1000),
    HORAS                  NUMBER(6,2),
    TIPO_ACTIVIDAD         VARCHAR2(80),
    EVIDENCIA              VARCHAR2(300),
    ESTADO                 VARCHAR2(20) DEFAULT 'REGISTRADO' NOT NULL,
    OBSERVACIONES          VARCHAR2(1000),
    CONSTRAINT PK_REGISTRO_ACTIVIDAD PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT FK_RA_MP FOREIGN KEY (ID_MATRICULA_PRACTICA) REFERENCES MATRICULA_PRACTICA(ID_MATRICULA_PRACTICA)
);

CREATE TABLE RESPUESTA (
    ID_RESPUESTA      NUMBER(10)      NOT NULL,
    ID_PREGUNTA       NUMBER(10)      NOT NULL,
    ID_ESTUDIANTE     NUMBER(10)      NOT NULL,
    RESPUESTA         VARCHAR2(1000),
    RETROALIMENTACION VARCHAR2(1000),
    FECHA_RESPUESTA   DATE DEFAULT SYSDATE,
    ESTADO            VARCHAR2(20) DEFAULT 'ENVIADA',
    CONSTRAINT PK_RESPUESTA PRIMARY KEY (ID_RESPUESTA),
    CONSTRAINT FK_RESP_PREGUNTA FOREIGN KEY (ID_PREGUNTA) REFERENCES PREGUNTA(ID_PREGUNTA),
    CONSTRAINT FK_RESP_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE LOG_ACTIVIDAD (
    ID_LOG        NUMBER(10) NOT NULL,
    TABLA_AFECTADA VARCHAR2(80),
    ACCION       VARCHAR2(40),
    ID_REGISTRO  NUMBER(10),
    VALOR_ANTERIOR VARCHAR2(1000),
    VALOR_NUEVO  VARCHAR2(1000),
    USUARIO_BD   VARCHAR2(80),
    FECHA_LOG    DATE DEFAULT SYSDATE,
    CONSTRAINT PK_LOG_ACTIVIDAD PRIMARY KEY (ID_LOG)
);

CREATE SEQUENCE SEQ_USUARIO START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROGRAMA START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CURSO START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GRUPO START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INSTITUCION START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRACTICA START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MATRICULA_PRACTICA START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ASIGNACION_DOCENTE START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RUBRICA START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CRITERIO_RUBRICA START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NIVEL_DESEMPENO START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EVALUACION START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PREGUNTA START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REGISTRO_ACTIVIDAD START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESPUESTA START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOG_ACTIVIDAD START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE INDEX IDX_USUARIO_TIPO ON USUARIO(TIPO_USUARIO);
CREATE INDEX IDX_PRACTICA_ESTADO ON PRACTICA(ESTADO);
CREATE INDEX IDX_MP_ESTUDIANTE ON MATRICULA_PRACTICA(ID_ESTUDIANTE);
CREATE INDEX IDX_MP_PRACTICA ON MATRICULA_PRACTICA(ID_PRACTICA);
CREATE INDEX IDX_RA_FECHA ON REGISTRO_ACTIVIDAD(FECHA_ACTIVIDAD);

COMMIT;
