-- ==========================================================
-- PROYECTOJD - Datos de prueba mínimos para ejecutar login y módulos
-- Contraseña para todos los usuarios: 123456
-- ==========================================================

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, TIPO_USUARIO, ESTADO, TELEFONO, DOCUMENTO)
VALUES (1, 'Director', 'Programa', 'admin@proyectojd.com', '123456', 'DIRECTOR', 'ACTIVO', '3000000001', '1001');

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, TIPO_USUARIO, ESTADO, TELEFONO, DOCUMENTO)
VALUES (2, 'Carlos', 'Coordinador', 'carlos@proyectojd.com', '123456', 'COORDINADOR', 'ACTIVO', '3000000002', '1002');

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, TIPO_USUARIO, ESTADO, TELEFONO, DOCUMENTO)
VALUES (3, 'Maria', 'Docente', 'maria@proyectojd.com', '123456', 'DOCENTE', 'ACTIVO', '3000000003', '1003');

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, TIPO_USUARIO, ESTADO, TELEFONO, DOCUMENTO)
VALUES (4, 'Juan', 'Estudiante', 'juan@proyectojd.com', '123456', 'ESTUDIANTE', 'ACTIVO', '3000000004', '1004');

INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, TIPO_USUARIO, ESTADO, TELEFONO, DOCUMENTO)
VALUES (5, 'Institucion', 'Receptora', 'empresa@proyectojd.com', '123456', 'INSTITUCION', 'ACTIVO', '3000000005', '900123456');

INSERT INTO INSTITUCION (ID_INSTITUCION, NOMBRE, DIRECCION, TELEFONO, EMAIL, NIT, CIUDAD, REPRESENTANTE, SITIO_WEB, FECHA_REGISTRO, ESTADO)
VALUES (1, 'Institucion Educativa Receptora', 'Calle 10 # 20-30', '6070000000', 'empresa@proyectojd.com', '900123456-1', 'Bucaramanga', 'Rector Institucional', 'www.institucion.edu.co', SYSDATE, 'ACTIVO');

INSERT INTO PROGRAMA (ID_PROGRAMA, NOMBRE, CODIGO, DESCRIPCION, FACULTAD, DURACION_SEMESTRES, ESTADO)
VALUES (1, 'Licenciatura en Educación Básica', 'LIC-001', 'Programa académico con prácticas pedagógicas supervisadas.', 'Facultad de Educación', 8, 'ACTIVO');

INSERT INTO CURSO (ID_CURSO, NOMBRE, CODIGO, CREDITOS, ID_PROGRAMA, DESCRIPCION, ESTADO)
VALUES (1, 'Practica Pedagogica I', 'PP-001', 3, 1, 'Curso asociado a la primera práctica académica.', 'ACTIVO');

INSERT INTO GRUPO (ID_GRUPO, NOMBRE, ID_CURSO, ID_DOCENTE, SEMESTRE, ANIO, ESTADO)
VALUES (1, 'Grupo A-2026', 1, 3, 'I', 2026, 'ACTIVO');

INSERT INTO PRACTICA (ID_PRACTICA, TITULO, DESCRIPCION, TIPO_PRACTICA, FECHA_INICIO, FECHA_FIN, ID_INSTITUCION, ID_CURSO, ID_GRUPO, HORAS_REQUERIDAS, ESTADO)
VALUES (1, 'Practica Pedagogica I', 'Seguimiento inicial del estudiante en institución receptora.', 'PEDAGOGICA', TO_DATE('2026-03-15','YYYY-MM-DD'), TO_DATE('2026-06-01','YYYY-MM-DD'), 5, 1, 1, 160, 'ACTIVO');

INSERT INTO MATRICULA_PRACTICA (ID_MATRICULA_PRACTICA, ID_ESTUDIANTE, ID_PRACTICA, ID_GRUPO, FECHA_MATRICULA, ESTADO)
VALUES (1, 4, 1, 1, SYSDATE, 'ACTIVO');

INSERT INTO ASIGNACION_DOCENTE (ID_ASIGNACION_DOCENTE, FECHA_ASIGNACION, ROL_EN_PRACTICA, ID_PRACTICA, ID_USUARIO, ESTADO)
VALUES (1, SYSDATE, 'Docente Asesor', 1, 3, 'ACTIVO');

INSERT INTO RUBRICA (ID_RUBRICA, NOMBRE, DESCRIPCION, ID_DOCENTE, ID_PRACTICA, PUNTAJE_TOTAL, FECHA_CREACION, ESTADO)
VALUES (1, 'Rubrica Practica Pedagogica I', 'Rubrica parametrizable para evaluación del desempeño.', 3, 1, 100, SYSDATE, 'ACTIVO');

INSERT INTO CRITERIO_RUBRICA (ID_CRITERIO, ID_RUBRICA, NOMBRE, DESCRIPCION, PUNTAJE_MAXIMO, PESO_PORCENTAJE, ORDEN, ESTADO)
VALUES (1, 1, 'Planeacion Pedagogica', 'Calidad de la planeación y preparación de actividades.', 25, 25, 1, 'ACTIVO');

INSERT INTO CRITERIO_RUBRICA (ID_CRITERIO, ID_RUBRICA, NOMBRE, DESCRIPCION, PUNTAJE_MAXIMO, PESO_PORCENTAJE, ORDEN, ESTADO)
VALUES (2, 1, 'Desempeno en Aula', 'Aplicación de estrategias didácticas durante la práctica.', 25, 25, 2, 'ACTIVO');

INSERT INTO CRITERIO_RUBRICA (ID_CRITERIO, ID_RUBRICA, NOMBRE, DESCRIPCION, PUNTAJE_MAXIMO, PESO_PORCENTAJE, ORDEN, ESTADO)
VALUES (3, 1, 'Responsabilidad', 'Cumplimiento de horarios, evidencias y compromisos.', 25, 25, 3, 'ACTIVO');

INSERT INTO CRITERIO_RUBRICA (ID_CRITERIO, ID_RUBRICA, NOMBRE, DESCRIPCION, PUNTAJE_MAXIMO, PESO_PORCENTAJE, ORDEN, ESTADO)
VALUES (4, 1, 'Reflexion Pedagogica', 'Capacidad de reflexión sobre el proceso formativo.', 25, 25, 4, 'ACTIVO');

INSERT INTO NIVEL_DESEMPENO (ID_NIVEL, ID_CRITERIO, NOMBRE, DESCRIPCION, PUNTAJE_MINIMO, PUNTAJE_MAXIMO, ESTADO)
VALUES (1, 1, 'Bajo', 'Requiere mejoramiento significativo.', 0, 2.9, 'ACTIVO');

INSERT INTO NIVEL_DESEMPENO (ID_NIVEL, ID_CRITERIO, NOMBRE, DESCRIPCION, PUNTAJE_MINIMO, PUNTAJE_MAXIMO, ESTADO)
VALUES (2, 1, 'Basico', 'Cumple parcialmente el criterio.', 3.0, 3.9, 'ACTIVO');

INSERT INTO NIVEL_DESEMPENO (ID_NIVEL, ID_CRITERIO, NOMBRE, DESCRIPCION, PUNTAJE_MINIMO, PUNTAJE_MAXIMO, ESTADO)
VALUES (3, 1, 'Alto', 'Cumple adecuadamente el criterio.', 4.0, 4.5, 'ACTIVO');

INSERT INTO NIVEL_DESEMPENO (ID_NIVEL, ID_CRITERIO, NOMBRE, DESCRIPCION, PUNTAJE_MINIMO, PUNTAJE_MAXIMO, ESTADO)
VALUES (4, 1, 'Superior', 'Supera ampliamente el criterio.', 4.6, 5.0, 'ACTIVO');

INSERT INTO EVALUACION (ID_EVALUACION, ID_MATRICULA_PRACTICA, ID_RUBRICA, ID_EVALUADOR, PUNTAJE_OBTENIDO, OBSERVACIONES, FECHA_EVALUACION, ESTADO)
VALUES (1, 1, 1, 3, 4.5, 'Evaluación inicial satisfactoria.', SYSDATE, 'REGISTRADA');

INSERT INTO PREGUNTA (ID_PREGUNTA, TEXTO_PREGUNTA, TIPO_PREGUNTA, PUNTAJE_MAXIMO, ORDEN, ID_EVALUACION, ID_PRACTICA, ESTADO)
VALUES (1, 'Describa la actividad pedagógica más significativa realizada durante la práctica.', 'ABIERTA', 5, 1, 1, 1, 'ACTIVO');

INSERT INTO REGISTRO_ACTIVIDAD (ID_REGISTRO, ID_MATRICULA_PRACTICA, FECHA_ACTIVIDAD, DESCRIPCION, HORAS, TIPO_ACTIVIDAD, EVIDENCIA, ESTADO, OBSERVACIONES)
VALUES (1, 1, SYSDATE, 'Observación de clase y apoyo pedagógico.', 4, 'OBSERVACION', 'evidencia_practica_001.pdf', 'APROBADO', 'Actividad validada por docente asesor.');

COMMIT;
