-- =============================================================
-- Funciones, procedimientos y disparadores de negocio/auditoría
-- Oracle 10g+
-- =============================================================
SET DEFINE OFF;

CREATE OR REPLACE FUNCTION FN_TOTAL_HORAS_ESTUDIANTE(p_id_estudiante NUMBER)
RETURN NUMBER IS
    v_total NUMBER := 0;
BEGIN
    SELECT NVL(SUM(R.HORAS),0)
    INTO v_total
    FROM REGISTRO_ACTIVIDAD R
    INNER JOIN MATRICULA_PRACTICA M ON R.ID_MATRICULA_PRACTICA = M.ID_MATRICULA_PRACTICA
    WHERE M.ID_ESTUDIANTE = p_id_estudiante
      AND NVL(UPPER(R.ESTADO),'APROBADO') IN ('APROBADO','CONFIRMADO','VALIDADO');
    RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION FN_ESTADO_HORAS(p_id_matricula NUMBER)
RETURN VARCHAR2 IS
    v_horas NUMBER := 0;
    v_requeridas NUMBER := 0;
BEGIN
    SELECT NVL(SUM(R.HORAS),0), NVL(MAX(NVL(P.HORAS_REGLAMENTARIAS, P.HORAS_REQUERIDAS)),0)
    INTO v_horas, v_requeridas
    FROM MATRICULA_PRACTICA M
    INNER JOIN PRACTICA P ON M.ID_PRACTICA = P.ID_PRACTICA
    LEFT JOIN REGISTRO_ACTIVIDAD R ON M.ID_MATRICULA_PRACTICA = R.ID_MATRICULA_PRACTICA
                               AND NVL(UPPER(R.ESTADO),'APROBADO') IN ('APROBADO','CONFIRMADO','VALIDADO')
    WHERE M.ID_MATRICULA_PRACTICA = p_id_matricula;
    IF v_horas >= v_requeridas THEN RETURN 'CUMPLE'; END IF;
    RETURN 'PENDIENTE';
END;
/

CREATE OR REPLACE FUNCTION FN_PROMEDIO_EVALUACION_PRACTICA(p_id_practica NUMBER)
RETURN NUMBER IS
    v_promedio NUMBER := 0;
BEGIN
    SELECT NVL(AVG(NVL(E.NOTA_EVALUACION, E.PUNTAJE_OBTENIDO)),0)
    INTO v_promedio
    FROM EVALUACION E
    INNER JOIN MATRICULA_PRACTICA M ON E.ID_MATRICULA_PRACTICA = M.ID_MATRICULA_PRACTICA
    WHERE M.ID_PRACTICA = p_id_practica;
    RETURN v_promedio;
END;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_ESTUDIANTES_PRACTICA(p_id_practica NUMBER)
RETURN NUMBER IS
    v_total NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_total
    FROM MATRICULA_PRACTICA
    WHERE ID_PRACTICA = p_id_practica
      AND NVL(UPPER(ESTADO),'ACTIVO') IN ('ACTIVO','PRODUCTIVA','FINALIZADO','APROBADO');
    RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION FN_GENERAR_HASH_CERT(p_id_matricula NUMBER)
RETURN VARCHAR2 IS
BEGIN
    RETURN 'CERT-' || p_id_matricula || '-' || TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS');
END;
/

CREATE OR REPLACE PROCEDURE SP_CREAR_USUARIO(
    p_nombre IN VARCHAR2, p_apellido IN VARCHAR2, p_email IN VARCHAR2,
    p_contrasena IN VARCHAR2, p_tipo_usuario IN VARCHAR2
) IS
BEGIN
    INSERT INTO USUARIO (NOMBRE, APELLIDO, EMAIL, CORREO, CONTRASENA, PASSWORD, TIPO_USUARIO, ROL, ESTADO)
    VALUES (p_nombre, p_apellido, p_email, p_email, p_contrasena, p_contrasena, UPPER(p_tipo_usuario), UPPER(p_tipo_usuario), 'ACTIVO');
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_MATRICULAR_ESTUDIANTE(
    p_id_estudiante IN NUMBER, p_id_practica IN NUMBER, p_id_grupo IN NUMBER, p_id_institucion IN NUMBER
) IS
BEGIN
    INSERT INTO MATRICULA_PRACTICA (ID_ESTUDIANTE, ID_USUARIO, ID_PRACTICA, ID_GRUPO, ID_INSTITUCION, FECHA_MATRICULA, ESTADO, ETAPA_ACADEMICA)
    VALUES (p_id_estudiante, p_id_estudiante, p_id_practica, p_id_grupo, p_id_institucion, SYSDATE, 'ACTIVO', 'ELECTIVA');
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_ACTIVIDAD(
    p_id_matricula IN NUMBER, p_id_usuario IN NUMBER, p_descripcion IN VARCHAR2,
    p_horas IN NUMBER, p_tipo IN VARCHAR2, p_evidencia IN VARCHAR2
) IS
BEGIN
    INSERT INTO REGISTRO_ACTIVIDAD (ID_MATRICULA_PRACTICA, ID_USUARIO, FECHA_ACTIVIDAD, DESCRIPCION, HORAS, TIPO_ACTIVIDAD, EVIDENCIA, ESTADO)
    VALUES (p_id_matricula, p_id_usuario, SYSDATE, p_descripcion, p_horas, p_tipo, p_evidencia, 'REGISTRADO');
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_EVALUACION(
    p_id_matricula IN NUMBER, p_id_rubrica IN NUMBER, p_id_evaluador IN NUMBER,
    p_nota IN NUMBER, p_observacion IN VARCHAR2
) IS
BEGIN
    INSERT INTO EVALUACION (ID_MATRICULA_PRACTICA, ID_RUBRICA, ID_EVALUADOR, NOTA_EVALUACION, PUNTAJE_OBTENIDO, OBSERVACIONES, FECHA_EVALUACION, ESTADO)
    VALUES (p_id_matricula, p_id_rubrica, p_id_evaluador, p_nota, p_nota, p_observacion, SYSDATE, 'REGISTRADA');
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_CAMBIAR_ETAPA_PRODUCTIVA(
    p_id_matricula IN NUMBER, p_id_usuario IN NUMBER, p_observacion IN VARCHAR2
) IS
    v_estado_anterior VARCHAR2(40);
BEGIN
    SELECT ETAPA_ACADEMICA INTO v_estado_anterior FROM MATRICULA_PRACTICA WHERE ID_MATRICULA_PRACTICA = p_id_matricula;
    IF FN_ESTADO_HORAS(p_id_matricula) <> 'CUMPLE' THEN
        RAISE_APPLICATION_ERROR(-20010, 'No se puede pasar a etapa productiva: horas incompletas.');
    END IF;
    UPDATE MATRICULA_PRACTICA SET ETAPA_ACADEMICA = 'PRODUCTIVA', ESTADO = 'PRODUCTIVA', HORAS_COMPLETAS = 1
    WHERE ID_MATRICULA_PRACTICA = p_id_matricula;
    INSERT INTO HISTORIAL_REVISION (ID_MATRICULA_PRACTICA, ID_USUARIO_REVISA, TIPO_REVISION, ESTADO_ANTERIOR, ESTADO_NUEVO, OBSERVACION)
    VALUES (p_id_matricula, p_id_usuario, 'CAMBIO_ETAPA', v_estado_anterior, 'PRODUCTIVA', p_observacion);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_EMITIR_CERTIFICADO(
    p_id_matricula IN NUMBER, p_id_usuario_emite IN NUMBER
) IS
BEGIN
    INSERT INTO CERTIFICADO_PRACTICA (ID_MATRICULA_PRACTICA, ID_USUARIO_EMITE, FECHA_EMISION, HASH_VERIFICACION, FIRMA_DIGITAL_SIMULADA, ESTADO)
    VALUES (p_id_matricula, p_id_usuario_emite, SYSDATE, FN_GENERAR_HASH_CERT(p_id_matricula), 'Firma digital simulada - Coordinación de Prácticas', 'EMITIDO');
    COMMIT;
END;
/

CREATE OR REPLACE TRIGGER TRG_REGISTRO_HORAS_VALIDAR
BEFORE INSERT OR UPDATE ON REGISTRO_ACTIVIDAD
FOR EACH ROW
BEGIN
    IF :NEW.HORAS IS NULL OR :NEW.HORAS < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Las horas de práctica no pueden ser negativas ni nulas.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EVALUACION_NOTA_VALIDAR
BEFORE INSERT OR UPDATE ON EVALUACION
FOR EACH ROW
BEGIN
    IF NVL(:NEW.NOTA_EVALUACION, NVL(:NEW.PUNTAJE_OBTENIDO,0)) < 0 OR NVL(:NEW.NOTA_EVALUACION, NVL(:NEW.PUNTAJE_OBTENIDO,0)) > 5 THEN
        RAISE_APPLICATION_ERROR(-20002, 'La nota de evaluación debe estar entre 0 y 5.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_MATRICULA
AFTER INSERT OR UPDATE OR DELETE ON MATRICULA_PRACTICA
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO LOG_ACTIVIDAD (ID_USUARIO, TABLA_AFECTADA, ID_REGISTRO, TIPO_OPERACION, ACCION, VALOR_NUEVO, MODULO)
        VALUES (:NEW.ID_ESTUDIANTE, 'MATRICULA_PRACTICA', TO_CHAR(:NEW.ID_MATRICULA_PRACTICA), 'INSERT', 'INSERT', 'ESTADO=' || :NEW.ESTADO || ';ETAPA=' || :NEW.ETAPA_ACADEMICA, 'TRIGGER');
    ELSIF UPDATING THEN
        INSERT INTO LOG_ACTIVIDAD (ID_USUARIO, TABLA_AFECTADA, ID_REGISTRO, TIPO_OPERACION, ACCION, VALOR_ANTERIOR, VALOR_NUEVO, MODULO)
        VALUES (:NEW.ID_ESTUDIANTE, 'MATRICULA_PRACTICA', TO_CHAR(:NEW.ID_MATRICULA_PRACTICA), 'UPDATE', 'UPDATE', 'ESTADO=' || :OLD.ESTADO || ';ETAPA=' || :OLD.ETAPA_ACADEMICA, 'ESTADO=' || :NEW.ESTADO || ';ETAPA=' || :NEW.ETAPA_ACADEMICA, 'TRIGGER');
    ELSE
        INSERT INTO LOG_ACTIVIDAD (ID_USUARIO, TABLA_AFECTADA, ID_REGISTRO, TIPO_OPERACION, ACCION, VALOR_ANTERIOR, MODULO)
        VALUES (:OLD.ID_ESTUDIANTE, 'MATRICULA_PRACTICA', TO_CHAR(:OLD.ID_MATRICULA_PRACTICA), 'DELETE', 'DELETE', 'ESTADO=' || :OLD.ESTADO, 'TRIGGER');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_EVALUACION
AFTER INSERT OR UPDATE OR DELETE ON EVALUACION
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO LOG_ACTIVIDAD (ID_USUARIO, TABLA_AFECTADA, ID_REGISTRO, TIPO_OPERACION, ACCION, VALOR_NUEVO, MODULO)
        VALUES (:NEW.ID_EVALUADOR, 'EVALUACION', TO_CHAR(:NEW.ID_EVALUACION), 'INSERT', 'INSERT', 'NOTA=' || NVL(:NEW.NOTA_EVALUACION, :NEW.PUNTAJE_OBTENIDO), 'TRIGGER');
    ELSIF UPDATING THEN
        INSERT INTO LOG_ACTIVIDAD (ID_USUARIO, TABLA_AFECTADA, ID_REGISTRO, TIPO_OPERACION, ACCION, VALOR_ANTERIOR, VALOR_NUEVO, MODULO)
        VALUES (:NEW.ID_EVALUADOR, 'EVALUACION', TO_CHAR(:NEW.ID_EVALUACION), 'UPDATE', 'UPDATE', 'NOTA=' || NVL(:OLD.NOTA_EVALUACION, :OLD.PUNTAJE_OBTENIDO), 'NOTA=' || NVL(:NEW.NOTA_EVALUACION, :NEW.PUNTAJE_OBTENIDO), 'TRIGGER');
    ELSE
        INSERT INTO LOG_ACTIVIDAD (ID_USUARIO, TABLA_AFECTADA, ID_REGISTRO, TIPO_OPERACION, ACCION, VALOR_ANTERIOR, MODULO)
        VALUES (:OLD.ID_EVALUADOR, 'EVALUACION', TO_CHAR(:OLD.ID_EVALUACION), 'DELETE', 'DELETE', 'NOTA=' || NVL(:OLD.NOTA_EVALUACION, :OLD.PUNTAJE_OBTENIDO), 'TRIGGER');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_DOCUMENTO
AFTER INSERT OR UPDATE ON DOCUMENTO_ESTUDIANTE
FOR EACH ROW
BEGIN
    INSERT INTO LOG_ACTIVIDAD (ID_USUARIO, TABLA_AFECTADA, ID_REGISTRO, TIPO_OPERACION, ACCION, VALOR_NUEVO, MODULO)
    VALUES (:NEW.ID_USUARIO_SUBE, 'DOCUMENTO_ESTUDIANTE', TO_CHAR(:NEW.ID_DOCUMENTO_ESTUDIANTE), CASE WHEN INSERTING THEN 'INSERT' ELSE 'UPDATE' END, CASE WHEN INSERTING THEN 'INSERT' ELSE 'UPDATE' END, 'ARCHIVO=' || :NEW.NOMBRE_ARCHIVO || ';ESTADO=' || :NEW.ESTADO, 'TRIGGER');
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_HISTORIAL
AFTER INSERT ON HISTORIAL_REVISION
FOR EACH ROW
BEGIN
    INSERT INTO LOG_ACTIVIDAD (ID_USUARIO, TABLA_AFECTADA, ID_REGISTRO, TIPO_OPERACION, ACCION, VALOR_NUEVO, MODULO)
    VALUES (:NEW.ID_USUARIO_REVISA, 'HISTORIAL_REVISION', TO_CHAR(:NEW.ID_HISTORIAL_REVISION), 'INSERT', 'INSERT', 'CAMBIO=' || :NEW.ESTADO_ANTERIOR || '->' || :NEW.ESTADO_NUEVO, 'TRIGGER');
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_CERTIFICADO
AFTER INSERT ON CERTIFICADO_PRACTICA
FOR EACH ROW
BEGIN
    INSERT INTO LOG_ACTIVIDAD (ID_USUARIO, TABLA_AFECTADA, ID_REGISTRO, TIPO_OPERACION, ACCION, VALOR_NUEVO, MODULO)
    VALUES (:NEW.ID_USUARIO_EMITE, 'CERTIFICADO_PRACTICA', TO_CHAR(:NEW.ID_CERTIFICADO_PRACTICA), 'INSERT', 'INSERT', 'HASH=' || :NEW.HASH_VERIFICACION, 'TRIGGER');
END;
/

COMMIT;
PROMPT Funciones, procedimientos y triggers instalados correctamente.
