-- ==========================================================
-- PROYECTOJD - Funciones, procedimientos y triggers Oracle 10g
-- ==========================================================

CREATE OR REPLACE FUNCTION FN_TOTAL_HORAS_ESTUDIANTE(p_id_estudiante NUMBER)
RETURN NUMBER IS
    v_total NUMBER := 0;
BEGIN
    SELECT NVL(SUM(R.HORAS),0)
    INTO v_total
    FROM REGISTRO_ACTIVIDAD R
    INNER JOIN MATRICULA_PRACTICA M ON R.ID_MATRICULA_PRACTICA = M.ID_MATRICULA_PRACTICA
    WHERE M.ID_ESTUDIANTE = p_id_estudiante
      AND R.ESTADO = 'APROBADO';

    RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_ESTUDIANTES_PRACTICA(p_id_practica NUMBER)
RETURN NUMBER IS
    v_total NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_total
    FROM MATRICULA_PRACTICA
    WHERE ID_PRACTICA = p_id_practica
      AND ESTADO IN ('ACTIVO','APROBADO');

    RETURN v_total;
END;
/

CREATE OR REPLACE FUNCTION FN_PROMEDIO_EVALUACION_PRACTICA(p_id_practica NUMBER)
RETURN NUMBER IS
    v_promedio NUMBER := 0;
BEGIN
    SELECT NVL(AVG(E.PUNTAJE_OBTENIDO),0)
    INTO v_promedio
    FROM EVALUACION E
    INNER JOIN MATRICULA_PRACTICA M ON E.ID_MATRICULA_PRACTICA = M.ID_MATRICULA_PRACTICA
    WHERE M.ID_PRACTICA = p_id_practica;

    RETURN v_promedio;
END;
/

CREATE OR REPLACE FUNCTION FN_ESTADO_HORAS(p_id_matricula NUMBER)
RETURN VARCHAR2 IS
    v_horas NUMBER := 0;
    v_requeridas NUMBER := 0;
BEGIN
    SELECT NVL(SUM(R.HORAS),0), NVL(MAX(P.HORAS_REQUERIDAS),0)
    INTO v_horas, v_requeridas
    FROM MATRICULA_PRACTICA M
    INNER JOIN PRACTICA P ON M.ID_PRACTICA = P.ID_PRACTICA
    LEFT JOIN REGISTRO_ACTIVIDAD R ON M.ID_MATRICULA_PRACTICA = R.ID_MATRICULA_PRACTICA
                                AND R.ESTADO = 'APROBADO'
    WHERE M.ID_MATRICULA_PRACTICA = p_id_matricula;

    IF v_horas >= v_requeridas THEN
        RETURN 'CUMPLE';
    ELSE
        RETURN 'PENDIENTE';
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE SP_CREAR_USUARIO(
    p_nombre       IN VARCHAR2,
    p_apellido     IN VARCHAR2,
    p_email        IN VARCHAR2,
    p_contrasena   IN VARCHAR2,
    p_tipo_usuario IN VARCHAR2
) IS
BEGIN
    INSERT INTO USUARIO (ID_USUARIO, NOMBRE, APELLIDO, EMAIL, CONTRASENA, TIPO_USUARIO, ESTADO)
    VALUES (SEQ_USUARIO.NEXTVAL, p_nombre, p_apellido, p_email, p_contrasena, p_tipo_usuario, 'ACTIVO');
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_MATRICULAR_ESTUDIANTE(
    p_id_estudiante IN NUMBER,
    p_id_practica   IN NUMBER,
    p_id_grupo      IN NUMBER
) IS
BEGIN
    INSERT INTO MATRICULA_PRACTICA (ID_MATRICULA_PRACTICA, ID_ESTUDIANTE, ID_PRACTICA, ID_GRUPO, FECHA_MATRICULA, ESTADO)
    VALUES (SEQ_MATRICULA_PRACTICA.NEXTVAL, p_id_estudiante, p_id_practica, p_id_grupo, SYSDATE, 'ACTIVO');
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_ACTIVIDAD(
    p_id_matricula IN NUMBER,
    p_descripcion  IN VARCHAR2,
    p_horas        IN NUMBER,
    p_tipo         IN VARCHAR2,
    p_evidencia    IN VARCHAR2
) IS
BEGIN
    INSERT INTO REGISTRO_ACTIVIDAD (ID_REGISTRO, ID_MATRICULA_PRACTICA, FECHA_ACTIVIDAD, DESCRIPCION, HORAS, TIPO_ACTIVIDAD, EVIDENCIA, ESTADO, OBSERVACIONES)
    VALUES (SEQ_REGISTRO_ACTIVIDAD.NEXTVAL, p_id_matricula, SYSDATE, p_descripcion, p_horas, p_tipo, p_evidencia, 'REGISTRADO', 'Pendiente de revisión');
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_EVALUACION(
    p_id_matricula IN NUMBER,
    p_id_rubrica   IN NUMBER,
    p_id_evaluador IN NUMBER,
    p_puntaje      IN NUMBER,
    p_observacion  IN VARCHAR2
) IS
BEGIN
    INSERT INTO EVALUACION (ID_EVALUACION, ID_MATRICULA_PRACTICA, ID_RUBRICA, ID_EVALUADOR, PUNTAJE_OBTENIDO, OBSERVACIONES, FECHA_EVALUACION, ESTADO)
    VALUES (SEQ_EVALUACION.NEXTVAL, p_id_matricula, p_id_rubrica, p_id_evaluador, p_puntaje, p_observacion, SYSDATE, 'REGISTRADA');
    COMMIT;
END;
/

CREATE OR REPLACE TRIGGER TRG_USUARIO_ESTADO
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.ESTADO IS NULL THEN
        :NEW.ESTADO := 'ACTIVO';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_REGISTRO_HORAS_VALIDAR
BEFORE INSERT OR UPDATE ON REGISTRO_ACTIVIDAD
FOR EACH ROW
BEGIN
    IF :NEW.HORAS IS NULL OR :NEW.HORAS < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Las horas de práctica no pueden ser negativas ni nulas.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EVALUACION_PUNTAJE_VALIDAR
BEFORE INSERT OR UPDATE ON EVALUACION
FOR EACH ROW
BEGIN
    IF :NEW.PUNTAJE_OBTENIDO < 0 OR :NEW.PUNTAJE_OBTENIDO > 100 THEN
        RAISE_APPLICATION_ERROR(-20002, 'El puntaje de evaluación debe estar entre 0 y 100.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_RUBRICA_TOTAL_VALIDAR
BEFORE INSERT OR UPDATE ON RUBRICA
FOR EACH ROW
BEGIN
    IF :NEW.PUNTAJE_TOTAL <= 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'El puntaje total de la rúbrica debe ser mayor que cero.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITORIA_EVALUACION
AFTER UPDATE ON EVALUACION
FOR EACH ROW
BEGIN
    INSERT INTO LOG_ACTIVIDAD (ID_LOG, TABLA_AFECTADA, ACCION, ID_REGISTRO, VALOR_ANTERIOR, VALOR_NUEVO, USUARIO_BD, FECHA_LOG)
    VALUES (SEQ_LOG_ACTIVIDAD.NEXTVAL, 'EVALUACION', 'UPDATE', :OLD.ID_EVALUACION,
            'PUNTAJE=' || :OLD.PUNTAJE_OBTENIDO || ' ESTADO=' || :OLD.ESTADO,
            'PUNTAJE=' || :NEW.PUNTAJE_OBTENIDO || ' ESTADO=' || :NEW.ESTADO,
            USER, SYSDATE);
END;
/

COMMIT;
