-- ==========================================================
-- PROYECTOJD - Consultas de prueba para validar CRUD básico
-- ==========================================================

-- READ
SELECT * FROM USUARIO ORDER BY ID_USUARIO;
SELECT * FROM PROGRAMA ORDER BY ID_PROGRAMA;
SELECT * FROM PRACTICA ORDER BY ID_PRACTICA;

-- CREATE
INSERT INTO PROGRAMA (ID_PROGRAMA, NOMBRE, CODIGO, DESCRIPCION, FACULTAD, DURACION_SEMESTRES, ESTADO)
VALUES (SEQ_PROGRAMA.NEXTVAL, 'Programa de Prueba', 'PRU-001', 'Registro creado para prueba CRUD.', 'Ingenieria', 8, 'ACTIVO');

-- UPDATE
UPDATE PROGRAMA SET DESCRIPCION = 'Registro actualizado desde prueba CRUD' WHERE CODIGO = 'PRU-001';

-- DELETE lógico
UPDATE PROGRAMA SET ESTADO = 'INACTIVO' WHERE CODIGO = 'PRU-001';

-- Funciones
SELECT FN_TOTAL_HORAS_ESTUDIANTE(4) AS TOTAL_HORAS FROM DUAL;
SELECT FN_TOTAL_ESTUDIANTES_PRACTICA(1) AS TOTAL_ESTUDIANTES FROM DUAL;
SELECT FN_PROMEDIO_EVALUACION_PRACTICA(1) AS PROMEDIO FROM DUAL;
SELECT FN_ESTADO_HORAS(1) AS ESTADO_HORAS FROM DUAL;

COMMIT;
