-- ==========================================================
-- PROYECTOJD - Roles y privilegios Oracle 10g
-- Ejecutar con usuario DBA si se requiere crear usuario desde cero.
-- ==========================================================

-- CREATE USER PROYECTOJD IDENTIFIED BY PROYECTOJD;
-- GRANT CONNECT, RESOURCE TO PROYECTOJD;
-- GRANT CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER, CREATE SEQUENCE TO PROYECTOJD;

-- Conectarse luego como:
-- CONNECT PROYECTOJD/PROYECTOJD@orcl

CREATE ROLE ROL_DIRECTOR_PROYECTOJD;
CREATE ROLE ROL_COORDINADOR_PROYECTOJD;
CREATE ROLE ROL_DOCENTE_PROYECTOJD;
CREATE ROLE ROL_ESTUDIANTE_PROYECTOJD;
CREATE ROLE ROL_INSTITUCION_PROYECTOJD;

GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIO TO ROL_DIRECTOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROGRAMA TO ROL_DIRECTOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE, DELETE ON CURSO TO ROL_DIRECTOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRACTICA TO ROL_DIRECTOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE, DELETE ON GRUPO TO ROL_DIRECTOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE, DELETE ON INSTITUCION TO ROL_DIRECTOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE, DELETE ON EVALUACION TO ROL_DIRECTOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE, DELETE ON RUBRICA TO ROL_DIRECTOR_PROYECTOJD;
GRANT SELECT ON LOG_ACTIVIDAD TO ROL_DIRECTOR_PROYECTOJD;

GRANT SELECT, INSERT, UPDATE ON GRUPO TO ROL_COORDINADOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE ON MATRICULA_PRACTICA TO ROL_COORDINADOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE ON ASIGNACION_DOCENTE TO ROL_COORDINADOR_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE ON INSTITUCION TO ROL_COORDINADOR_PROYECTOJD;

GRANT SELECT, INSERT, UPDATE ON EVALUACION TO ROL_DOCENTE_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE ON RUBRICA TO ROL_DOCENTE_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE ON CRITERIO_RUBRICA TO ROL_DOCENTE_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE ON NIVEL_DESEMPENO TO ROL_DOCENTE_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE ON PREGUNTA TO ROL_DOCENTE_PROYECTOJD;
GRANT SELECT, UPDATE ON REGISTRO_ACTIVIDAD TO ROL_DOCENTE_PROYECTOJD;

GRANT SELECT, INSERT, UPDATE ON REGISTRO_ACTIVIDAD TO ROL_ESTUDIANTE_PROYECTOJD;
GRANT SELECT, INSERT, UPDATE ON RESPUESTA TO ROL_ESTUDIANTE_PROYECTOJD;
GRANT SELECT ON EVALUACION TO ROL_ESTUDIANTE_PROYECTOJD;
GRANT SELECT ON PREGUNTA TO ROL_ESTUDIANTE_PROYECTOJD;

GRANT SELECT, UPDATE ON REGISTRO_ACTIVIDAD TO ROL_INSTITUCION_PROYECTOJD;
GRANT SELECT ON MATRICULA_PRACTICA TO ROL_INSTITUCION_PROYECTOJD;
GRANT SELECT ON PRACTICA TO ROL_INSTITUCION_PROYECTOJD;

COMMIT;
