-- ==========================================================
-- PROYECTOJD - Actualización opcional para mejoras de UI
-- Ejecutar solo si la base de datos ya existe y se desean usar
-- estados ampliados, foto de perfil, logo de institución e historial.
-- Compatible con Oracle 10g / SQL*Plus.
-- ==========================================================

-- 1) Foto de perfil para usuarios del sistema.
DECLARE
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'USUARIO'
      AND COLUMN_NAME = 'FOTO_PERFIL';

    IF V_EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USUARIO ADD FOTO_PERFIL VARCHAR2(300)';
    END IF;
END;
/

-- 2) Logo de la institución receptora.
DECLARE
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'INSTITUCION'
      AND COLUMN_NAME = 'LOGO';

    IF V_EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE INSTITUCION ADD LOGO VARCHAR2(300)';
    END IF;
END;
/

-- 3) Historial básico de revisión de actividades/evidencias.
DECLARE
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'REGISTRO_ACTIVIDAD'
      AND COLUMN_NAME = 'REVISADO_POR';

    IF V_EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE REGISTRO_ACTIVIDAD ADD REVISADO_POR NUMBER(10)';
    END IF;
END;
/

DECLARE
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'REGISTRO_ACTIVIDAD'
      AND COLUMN_NAME = 'FECHA_REVISION';

    IF V_EXISTE = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE REGISTRO_ACTIVIDAD ADD FECHA_REVISION DATE';
    END IF;
END;
/

-- 4) Permitir estados de proceso para institución receptora.
-- Si existe restricción CK_INSTITUCION_ESTADO antigua, se reemplaza.
DECLARE
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'INSTITUCION'
      AND CONSTRAINT_NAME = 'CK_INSTITUCION_ESTADO';

    IF V_EXISTE > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE INSTITUCION DROP CONSTRAINT CK_INSTITUCION_ESTADO';
    END IF;
END;
/

ALTER TABLE INSTITUCION
ADD CONSTRAINT CK_INSTITUCION_ESTADO
CHECK (ESTADO IN ('ACTIVO','INACTIVO','PENDIENTE','APROBADO','REPROBADO'));

COMMIT;
